### ndarray 다루기(1)

In [2]:
import numpy as np

#### 데이터 벡터 x를 만드시오

In [3]:
x = np.array([[2,3,5,6,7,10]])

In [4]:
x

array([[ 2,  3,  5,  6,  7, 10]])

#### 각 데이터의 제곱으로 구성된 벡터 x2를 만드시오

In [5]:
x2 = x ** 2

In [6]:
x2

array([[  4,   9,  25,  36,  49, 100]], dtype=int32)

#### 각 데이터의 제곱의 합을 구하시오

In [7]:
sum =0
for i in x2[0]:
    sum += i
    

In [8]:
sum

223

#### 각 데이터에서 2를 뺀 값을 구하시오

In [9]:
x-2

array([[0, 1, 3, 4, 5, 8]])

#### 최대값과 최소값을 구하시오

In [10]:
max(x[0]) # 최대값

10

In [11]:
min(x[0]) # 최소값

2

#### 5보다 큰 값들로만 구성된 데이터 벡터 x_up을 만드시오

In [12]:
x_up = x[x > 5]
x_up

array([ 6,  7, 10])

#### 벡터 x의 길이를 구하시오

In [13]:
len(x[0])

6

#### x'x를 구하시오 (x'는 x의 전치)

In [14]:
np.transpose(x) * x

array([[  4,   6,  10,  12,  14,  20],
       [  6,   9,  15,  18,  21,  30],
       [ 10,  15,  25,  30,  35,  50],
       [ 12,  18,  30,  36,  42,  60],
       [ 14,  21,  35,  42,  49,  70],
       [ 20,  30,  50,  60,  70, 100]])

#### xx'를 구하시오

In [15]:
x * np.transpose(x)

array([[  4,   6,  10,  12,  14,  20],
       [  6,   9,  15,  18,  21,  30],
       [ 10,  15,  25,  30,  35,  50],
       [ 12,  18,  30,  36,  42,  60],
       [ 14,  21,  35,  42,  49,  70],
       [ 20,  30,  50,  60,  70, 100]])

#### 벡터 x와 x2를 열결합(column bind)하여 xc에 저장하시오

In [16]:
xc = np.concatenate((x,x2),axis=1)  #axis=1 열결합
xc

array([[  2,   3,   5,   6,   7,  10,   4,   9,  25,  36,  49, 100]])

#### 벡터 x와 x2를 행결합(row bind)하여 xr에 저장하시오

In [17]:
xr = np.concatenate((x,x2),axis=0) #axis=0 행결합
xr

array([[  2,   3,   5,   6,   7,  10],
       [  4,   9,  25,  36,  49, 100]])

### ndarray 다루기(2)

#### 표준정규분포를 따르는 난수 100개를 가진 배열 x를 만드시오

In [18]:
x = np.random.randn(100)
x

array([-5.29946089e-01,  1.26823946e+00,  1.10811286e+00, -5.18751328e-02,
        1.31912840e+00,  3.70701869e-01,  7.74634987e-01, -1.96964776e-01,
       -5.90395993e-01, -1.53017154e+00,  2.24673120e-01,  2.30268015e+00,
       -2.06504044e+00,  4.61607314e-01,  9.80253990e-01,  1.17672788e+00,
       -5.32284214e-01, -1.00339695e+00, -6.68383778e-02, -7.64607919e-01,
       -8.89740924e-01, -1.26157740e+00, -1.55972502e-01, -1.20902567e+00,
        1.29717993e-01,  8.63041288e-01, -1.62244544e+00,  1.60829554e-01,
        1.23938399e-01,  2.60692047e-01, -8.76661087e-01,  8.88774093e-01,
        1.06699364e+00, -7.17173839e-01,  1.61007618e+00, -1.21302287e+00,
        7.09469890e-01, -3.37231274e-01,  1.21706611e+00, -1.30793913e+00,
        3.38779165e-01, -6.26350074e-01,  5.54836392e-01, -8.33679531e-01,
       -1.66737776e+00,  5.99600423e-02,  2.52763214e+00, -7.84633126e-03,
       -1.74229010e+00, -2.42819618e-01, -1.77730638e+00,  7.65856083e-01,
       -1.57158633e+00,  

#### x에서 값이 0.2보다 큰 원소들을 골라내시오

In [21]:
np.where(x > 0.2,x,False) #이렇게 하던가
e = x[x>0.2]
e

array([1.26823946, 1.10811286, 1.3191284 , 0.37070187, 0.77463499,
       0.22467312, 2.30268015, 0.46160731, 0.98025399, 1.17672788,
       0.86304129, 0.26069205, 0.88877409, 1.06699364, 1.61007618,
       0.70946989, 1.21706611, 0.33877917, 0.55483639, 2.52763214,
       0.76585608, 2.11446658, 0.52152524, 1.09377834, 0.62938457,
       0.56188945, 1.22669535, 0.57800518, 0.87792837, 0.25489628,
       1.47557388, 0.34008205, 0.68928548, 0.97252421, 1.25590454,
       0.40034514, 1.86713107, 0.7918406 , 1.32596263, 0.56488803,
       1.1328196 ])

### 선형방정식 풀기(해 구하기)

#### 다음과 같은 방정식이 있다. 

#### 3x + 6y - 5z = 12x - 3y + 2z = -25x - y + 4z = 10

#### 위 식을 numpy를 이용해서 Ax=B 형태로 나타내시오(A와 B만 생성)

In [22]:
A = np.array([[3,6,-5],[12,-3,2],[-25,-1,4]])
B = np.array([[10],[10],[10]])

In [23]:
A

array([[  3,   6,  -5],
       [ 12,  -3,   2],
       [-25,  -1,   4]])

In [24]:
B

array([[10],
       [10],
       [10]])

#### A의 역행렬을 구하시오

In [25]:
np.linalg.inv(A)

array([[0.05464481, 0.10382514, 0.01639344],
       [0.53551913, 0.61748634, 0.36065574],
       [0.47540984, 0.80327869, 0.44262295]])

#### 방정식의 해 벡터 x를 구하시오

In [26]:
np.linalg.solve(A,B)

array([[ 1.74863388],
       [15.13661202],
       [17.21311475]])