### ndarray 다루기(1)

In [17]:
import numpy as np

#### 데이터 벡터 x를 만드시오

In [18]:
x = np.array([[2,3,5,6,7,10]])

In [19]:
x

array([[ 2,  3,  5,  6,  7, 10]])

#### 각 데이터의 제곱으로 구성된 벡터 x2를 만드시오

In [20]:
x2 = x ** 2

In [21]:
x2

array([[  4,   9,  25,  36,  49, 100]], dtype=int32)

#### 각 데이터의 제곱의 합을 구하시오

In [22]:
np.sum(x2)

223

#### 각 데이터에서 2를 뺀 값을 구하시오

In [23]:
x-2

array([[0, 1, 3, 4, 5, 8]])

#### 최대값과 최소값을 구하시오

In [24]:
np.max(x)

10

In [25]:
np.min(x)

2

#### 5보다 큰 값들로만 구성된 데이터 벡터 x_up을 만드시오

In [26]:
x_up = np.array([x[x>5]])
x_up

array([[ 6,  7, 10]])

#### 벡터 x의 길이를 구하시오

In [27]:
np.sqrt(x2.sum())

14.933184523068078

#### x'x를 구하시오 (x'는 x의 전치)

In [28]:
np.transpose(x) * x #혹은 np.transpose(x) ==  x.T

array([[  4,   6,  10,  12,  14,  20],
       [  6,   9,  15,  18,  21,  30],
       [ 10,  15,  25,  30,  35,  50],
       [ 12,  18,  30,  36,  42,  60],
       [ 14,  21,  35,  42,  49,  70],
       [ 20,  30,  50,  60,  70, 100]])

#### xx'를 구하시오

In [29]:
x * np.transpose(x)

array([[  4,   6,  10,  12,  14,  20],
       [  6,   9,  15,  18,  21,  30],
       [ 10,  15,  25,  30,  35,  50],
       [ 12,  18,  30,  36,  42,  60],
       [ 14,  21,  35,  42,  49,  70],
       [ 20,  30,  50,  60,  70, 100]])

#### 벡터 x와 x2를 열결합(column bind)하여 xc에 저장하시오

In [30]:
xc = np.concatenate((x,x2),axis=1)  #axis=1 열결합
xc

array([[  2,   3,   5,   6,   7,  10,   4,   9,  25,  36,  49, 100]])

#### 벡터 x와 x2를 행결합(row bind)하여 xr에 저장하시오

In [31]:
xr = np.concatenate((x,x2),axis=0) #axis=0 행결합
xr

array([[  2,   3,   5,   6,   7,  10],
       [  4,   9,  25,  36,  49, 100]])

### ndarray 다루기(2)

#### 표준정규분포를 따르는 난수 100개를 가진 배열 x를 만드시오

In [32]:
x = np.random.randn(100)
x

array([-0.71430895, -0.23974313,  0.60716002,  0.94302096,  0.76642462,
        0.91541648,  0.28285685, -0.69731957, -0.17444962, -1.2311783 ,
        0.49755329,  0.93683972, -0.3004443 ,  0.12501309,  0.20788602,
       -0.26174184, -1.76571791,  0.02542729,  0.87068846,  0.3388034 ,
       -0.44157324,  1.7779346 , -0.9836166 , -0.5378077 ,  1.25179847,
        2.12493943, -0.21471271,  2.31038151,  0.29773259,  1.13745601,
       -0.13340282, -1.36981919,  0.31618954,  1.0308909 ,  0.02529046,
        0.7617647 ,  1.44957032,  0.45998618, -0.53407702, -2.43384237,
        1.27320406, -1.71179137,  1.14460412,  0.46600967, -1.02509755,
        0.00314568,  0.55316768,  0.33949406,  1.34635428,  0.53985139,
       -0.46118376,  0.11778314,  0.29920947, -0.28915858, -0.71590925,
       -1.72267235, -2.10340934, -0.48830527, -1.81423861,  0.05064499,
       -0.20989235,  0.69661246,  0.38378781,  1.28537878, -0.99035849,
        0.19618723,  0.78483782, -2.63332046,  1.34636993,  0.55

#### x에서 값이 0.2보다 큰 원소들을 골라내시오

In [33]:
# np.where(x > 0.2,x,False) #이렇게 하던가
e = x[x>0.2]
e

array([0.60716002, 0.94302096, 0.76642462, 0.91541648, 0.28285685,
       0.49755329, 0.93683972, 0.20788602, 0.87068846, 0.3388034 ,
       1.7779346 , 1.25179847, 2.12493943, 2.31038151, 0.29773259,
       1.13745601, 0.31618954, 1.0308909 , 0.7617647 , 1.44957032,
       0.45998618, 1.27320406, 1.14460412, 0.46600967, 0.55316768,
       0.33949406, 1.34635428, 0.53985139, 0.29920947, 0.69661246,
       0.38378781, 1.28537878, 0.78483782, 1.34636993, 0.55382131,
       1.08334837, 0.34380742, 1.75928274, 0.32882683, 0.33121339,
       0.28420643, 0.22803124, 0.62450902, 0.51631946, 0.68896142,
       2.13609484, 1.1679124 , 0.87984081, 1.00024418, 0.54834308])

### 선형방정식 풀기(해 구하기)

#### 다음과 같은 방정식이 있다. 

#### 3x + 6y - 5z = 12x - 3y + 2z = -25x - y + 4z = 10

#### 위 식을 numpy를 이용해서 Ax=B 형태로 나타내시오(A와 B만 생성)

In [34]:
A = np.array([[3,6,-5],[12,-3,2],[-25,-1,4]])
B = np.array([[10],[10],[10]])

In [35]:
A

array([[  3,   6,  -5],
       [ 12,  -3,   2],
       [-25,  -1,   4]])

In [36]:
B

array([[10],
       [10],
       [10]])

#### A의 역행렬을 구하시오

In [37]:
np.linalg.inv(A)

array([[0.05464481, 0.10382514, 0.01639344],
       [0.53551913, 0.61748634, 0.36065574],
       [0.47540984, 0.80327869, 0.44262295]])

#### 방정식의 해 벡터 x를 구하시오

In [38]:
np.linalg.solve(A,B)

array([[ 1.74863388],
       [15.13661202],
       [17.21311475]])